apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-app.yaml
  - recipeservice-app-service.yaml
  - recipeservice-app-config.yaml
  - recipeservice-app-secrets.yaml
  - recipedb-owner-secret.yaml
  - deployment-web.yaml
  - recipeservice-web-service.yaml
  - ingress.yaml

images:
  - name: cookbook-server
    newName: docker.io/tommannson/recipeapp-backend
    newTag: 0.0.4
  - name: cookbook-prisma
    newName: docker.io/tommannson/recipeapp-db
    newTag: 0.0.2
  - name: cookbook-web
    newName: docker.io/tommannson/recipeapp-web
    newTag: 0.0.3


configMapGenerator:
  - name: cookbook-web-config
    files:
      - config.js
