apiVersion: v1
kind: Secret
metadata:
    name: tk-recipeservice-prisma-secret
type: Opaque
stringData:
    DATABASE_OWNER_URL: ENC[AES256_GCM,data:CZ768kjzSa6RnOhP624l5YmfMnSCwOtvWjbyZyletwRc7436MnpSpMLED/XMsG67jl1ZALaM0SnSYoZiNqrkfH218kKK9vjlsuijmLA/s71AClf9WEO9alHWS56+TZpp4Pzpi1gI7pTsmRN0O+64MuHf,iv:JroC2wIiiwbYZdYfuPb4OyJPAP7pVtc3kgTmtFu2nC4=,tag:WVYOlzfvOA/JbhpFMbHJcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQTA0USs3d3lKZWhHYTdI
            QUpjeFhsbmhrVXp2a0ZyeUFoZndDdDByd0hRCjZ2QlZURjdCNHRHQVVhRjdVaFlP
            M2ZoWlYwZjBqcTkrQWg3ZWJiaGp1WVEKLS0tIHgzMUNvVllxeFdJTzFvb1QxRVB0
            VDdDMkhGcU81WGJkM252b0xkamt5b3cKjt21PbKXu1Lg+2MVoHzckNLOraJhdgFA
            1AfxJUl5ElVMZj7KG27BDTPfBmx16b8IQvgsDjsuFf6WoCYzj4qU1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10fxsujcvpt6m4kwt36v7y7ljg7utgucwcq40hq9j2r5emay2gcwse9z20m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T20:48:59Z"
    mac: ENC[AES256_GCM,data:mROqwqMPEeiDnrkn1G9M5BUA/AU/bIgorFRJ3i8S/b5aJtsbDaZEAshGMBCokjseo7qalqPcNEgpzYwPQtZlJnfPcRwnDPAlas8Jv4fy0pQSWGQn76PcVM2hY+vwlPGo8tRTmTWGP+KN1A9YqctRK4FL6E49SMCcp1Qx0zc4zos=,iv:O2Z9oxNl4lA5ThnlSr7o/FphhPHMs64QRTzWI4N7kGU=,tag:3G8aT7XLO/vUb+Om+H2tLQ==,type:str]
    version: 3.13.0
