apiVersion: v1
kind: Secret
metadata:
    name: tk-recipeservice-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:nswtpWSt0KKYsqbYFhoW2J206VqRvK1NHcC4leOKcPwN0XJzJVbV3ob+oj19Z/iJFlEVivzCBND+zlbCDfk8VZviPV/nyGiGOfOzm9ZUame/FngvQ6EtQjlUoNgYhJRpf7L88FtG2DFLjHVHuw==,iv:ieTjg39jq5/PsorEplFuJETtsqNb7Ul1INE1gt3TXwA=,tag:+4uesH+SOhJKLVDgjkO+HA==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:MSSoXmIj3GAwKMcUhKzC+XXkGytSizP1x10u+7BevuX79R4H2jntglJJ2yU=,iv:2q/6AI23LBnhZrnbN9VkR2w4STc8XeogOkQ9LgO98ic=,tag:VcBXWf76ddKqNeYvSWQbHw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:097qit/4Xma8F1ntlIWQREnR499KlFtFKUDOyM3Ai4oRTY6RmbxmbmqPH2hwVzD+7FKujwYIhpXwgsBvLkbZ5s4j11XNeX/X,iv:I77D5fDqnLzgZlk0EYFT+v1bvPMLkx2crO67cfJt/Wo=,tag:IvV3/CGADOp3GHRWXsXk8A==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:d+zVFxhoXV53Z6z8BbskBKmvkED12rjUFIlsCmFPalL5pr0=,iv:Xv/z1Gt9oOa6mSvRV4kciv8mYrREi/vPhyCF+cv5F1g=,tag:Y+ibkCw3v39nTub3+GK3ZA==,type:str]
    ALLOWED_EMAILS: ENC[AES256_GCM,data:WFnh4ofdecYqNfD3YO/XS1SM9obLinQ=,iv:UZbouq4QnGb1Ai+GVpUw07aXF7FlhpeKNlP3f6tP6xg=,tag:1jTvgVRQCXrAlw7+9nlm6w==,type:str]
    LOGIN_PAGE_KEY: ENC[AES256_GCM,data:lmAGZBrtpOWi,iv:o2S8AvqZUaF/76ms0NVxzYtvfnl8iefhS+2c0tXzcpw=,tag:JOADkwLhbWDrm0CVZuYSXQ==,type:str]
    R2_ENDPOINT: ENC[AES256_GCM,data:9vQqFdEgCdH/8llRDr9aE6b2ZwdiT8dkPKn6CtVj6U+96mSLQqNAy0c=,iv:nP6KLFEPaIoA/WXPYFcECfmnU1Bri5rFCGarzRYFCJE=,tag:vwSXt1yMiHAGie9ozKIFYg==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:ssbLMVQ6jkhJ0jOK3RgD/uwnaLYQGIt6iQ==,iv:culhs4QWpncSXnfBMM7V/DztBB3gdfydsYgzJvovx7Y=,tag:MonQ/+dvsqw1FHmiTSbfSQ==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:V/Zarn8d4+eSJBLzVk+FIwPGpm4bXWu85QsUbin7ww==,iv:g2wUygUAF13NTaiCHoU6sVBghojtDonX8Ts+bmyL8Yg=,tag:nMwGXRJAE2udqffFqqrmgg==,type:str]
    R2_BUCKET: ENC[AES256_GCM,data:ITLHDXWi6B69Zg==,iv:yAmuGCx8lxFGRxetjT4Op+fU4IvnVJCEO5IiD3WWx10=,tag:P34f+BzCXYZ9b2arIm4MMA==,type:str]
    R2_PUBLIC_URL: ENC[AES256_GCM,data:vnaCCE8CBl780PLFqai+D/5t6AEkF7x34WkulPxEltxAZiG6iCow71tnZPMPTcbd58qfPw==,iv:foAKtLyZsmIivQKF59GsTCwacwUf0pNQ6sSWbaCTujQ=,tag:M3ZP4TR5rrh8xv308HkZTA==,type:str]
    MAKE_WEBHOOK_URL: ENC[AES256_GCM,data:RIb3HLzu1bq3jtzCXQt6EGrpCQkhJDDg+9K2RADLkZ0Q77UtETQyuNHVy1G70q/TlzGXiRF7etW65w==,iv:pPY0Jav/TiYssneC6sCUfXRHu0odx+K55caMfvcoPXo=,tag:R8V/NDB4aRJFkH1ebSSfKw==,type:str]
    GOOGLE_VISION_API_KEY: ENC[AES256_GCM,data:Ns8Py41FQk6qw8BxOcT6IfuoNlRtmX9xrM+NjS4MAs9AIc5w+DFU,iv:L14Ynym5Z01PWqoFieywdqFYPcb1F8qilB+hAln9O/s=,tag:Kj0eXc8QeWdefaC8onHQzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bklzeUdCVDVQTjVCblNm
            TkRUck85S2FSdE9VU3dNRjh5Y1VYV0RHR3pZCnNmRWhJZmFneHhwRllBOHJQa0NY
            bW1qTzNENnhzbVUyN1U5U1Y5bHFCbUEKLS0tIEFhWDRzSkdPZG1LeHd1RzI3NWFm
            K2RjUTdjbGxYQjMwVTZja2gyVTAxeWcKeHAzJlJWjj6eOpfrkkYybWTKct9SHChl
            l+O0GvxuMBQYroYWzaTrlvd7iZ3F0oSVW+mKzMDu6GuPxdYbHBFxzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10fxsujcvpt6m4kwt36v7y7ljg7utgucwcq40hq9j2r5emay2gcwse9z20m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T13:55:02Z"
    mac: ENC[AES256_GCM,data:SktcCucy2oG2zBmIWrrMsCBm2xn79ENuhk9K06y3q9a5ArzNYXeKUJkIc11r/yp3yUDVr/s4hbB1Jex5HrYpfn8U1Md57I4UoPtdAQ+oXu8gDjSjrqfssWbqW/HYynafFtnS0G7r3VxkZnzt5yhhjKc2D4HIR10S4UDWxpAteGg=,iv:MwTsL6OfHzC7TtZ5USc3wq9gdN0G76Km9i2JhPnNRE4=,tag:lxXy/QgEtRwp+QuNIjSJuQ==,type:str]
    version: 3.13.0
