apiVersion: v1
kind: Secret
metadata:
    name: cookbook-server-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:UvvARiGSfcndWKVfBUKZ9aeH1yjKp7mnH8q70dAdV6/wKV+WAtslJO117SZidoyR9+Z+tv4gbyO7ItFcLqR3VC3Hqyn9zw05GyDvpH3+u5lZzgTeH+03kJcVCgubGkLxlx68OSxZgzKlcI3cuw==,iv:vkaYtCVfPOZ8C5RnZkC3SbbmiyKwq4smZ589LU7BqHw=,tag:4A19/Oa3t2eoKsxYa7unCg==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:84O31Gpqaep1RSIhFY1vtKM9toINiPxb,iv:/tGcpK9whQZbuxuzw/1bIvkBmzziMQ4qJhy1z/Vgc3o=,tag:t/Mhe4H4cFvoSU5h5Ni39w==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:jA+BL6HBNgL4VQCgtlcr0AEFiyQ6Eo6NjBqM0qtbhX9cog==,iv:AO0qgmXummb+wyNFroibLhKQJgLXoPonmlwR04PE/GM=,tag:k9xSLA35vl2T0t89OPSmDA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:1b2QCqqU/Q==,iv:YLYm6vy2dpkeiksI2pJ6WPzIpBeVs+fMkTRRagspQaA=,tag:ua2wqZlaVffxkfq15qSBMw==,type:str]
    ALLOWED_EMAILS: ENC[AES256_GCM,data:7J6HnYnLEs0dPOGUKnuS4KpVbkS/tfk=,iv:vziLmcybNI2qiF9SNMmTxyJPT59Yh6Oeam9awRJ0d38=,tag:q9lfq6HXsSz/k8WUAAuT4Q==,type:str]
    LOGIN_PAGE_KEY: ENC[AES256_GCM,data:j3VveaJ22kjuJHT4kIUd7bWjzqO4S4w=,iv:OVrtIkafwEwAwaizKSPCwLR1yXtwdLbw5Wbs+9RC178=,tag:mxtBivgjVvftxu6QNV134A==,type:str]
    R2_ENDPOINT: ENC[AES256_GCM,data:DwSFlsxhnEFRPrbE8tTGT8QEq2ES/WpfKS4iTrGto1U8ZtXJlI8E9hoT44k=,iv:wO59k81RzfN6N+gDkmZQGaoBYszmDXCKjEbJ875oPUk=,tag:WPLssX5NeMVaRwK/9u+wiA==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:pHO3Qq9HFA==,iv:mJePl8XgfdbZq+DEi/CQhlKN9ypYMxvjci9Ib8Ocsuk=,tag:o0dy+VDdpB9piMaa4xx73Q==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3BYzhErQrQ==,iv:MTryWISAkSyl+rA5n9W+MbJQ9uaicI+v3uOsnZMezyc=,tag:HZEZgTqjAxajwOtjhAu9jg==,type:str]
    R2_BUCKET: ENC[AES256_GCM,data:ST/rASSBwJn8zsmnq8U=,iv:8nTFAjyzB/LaYUxX7cdtNdUHYpvzwcEvWgiZnaXOl7g=,tag:wzISSWSk9Vcyz3BwxrUXAg==,type:str]
    R2_PUBLIC_URL: ENC[AES256_GCM,data:U3GQM7R1NTWL3BVrOrEGgUaqF9dr3NLruQ==,iv:wh3gg16yz1A3pzlMpZqJQhh6kTDfNc+Hbixib4CQ5ZY=,tag:EwwwiWVeUq3X1x4W3jo2Jg==,type:str]
    MAKE_WEBHOOK_URL: ENC[AES256_GCM,data:izAdEQspuluT139asmREGUdyi0bEWNZ05rpiI+fXaEi7,iv:GwlqtrgRpkmHm6MtdnAsQurl38LrbkclJlGQr9fEMig=,tag:2gD7Y5HGYrbHdeMB9ELlBA==,type:str]
    GOOGLE_VISION_API_KEY: ENC[AES256_GCM,data:Qcgt+t+Dcw==,iv:zafL7XKcp2PXVnfwjGf52bon0F45YGDTG+LEeyt0yI0=,tag:vbmsVU+pXMTU0nMLOHDw+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bklzeUdCVDVQTjVCblNm
            TkRUck85S2FSdE9VU3dNRjh5Y1VYV0RHR3pZCnNmRWhJZmFneHhwRllBOHJQa0NY
            bW1qTzNENnhzbVUyN1U5U1Y5bHFCbUEKLS0tIEFhWDRzSkdPZG1LeHd1RzI3NWFm
            K2RjUTdjbGxYQjMwVTZja2gyVTAxeWcKeHAzJlJWjj6eOpfrkkYybWTKct9SHChl
            l+O0GvxuMBQYroYWzaTrlvd7iZ3F0oSVW+mKzMDu6GuPxdYbHBFxzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10fxsujcvpt6m4kwt36v7y7ljg7utgucwcq40hq9j2r5emay2gcwse9z20m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T13:55:02Z"
    mac: ENC[AES256_GCM,data:SktcCucy2oG2zBmIWrrMsCBm2xn79ENuhk9K06y3q9a5ArzNYXeKUJkIc11r/yp3yUDVr/s4hbB1Jex5HrYpfn8U1Md57I4UoPtdAQ+oXu8gDjSjrqfssWbqW/HYynafFtnS0G7r3VxkZnzt5yhhjKc2D4HIR10S4UDWxpAteGg=,iv:MwTsL6OfHzC7TtZ5USc3wq9gdN0G76Km9i2JhPnNRE4=,tag:lxXy/QgEtRwp+QuNIjSJuQ==,type:str]
    version: 3.13.0
