apiVersion: v1
kind: Secret
metadata:
    name: tk-recipeservice-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:19IgQ3+Khb843703dx6u/0IZEtlqvPNkn04S5xPjFnRVTMRsPqj4/0/9CXqUne2LmNiuZytWdzd4XubHo6cp+Js910nbW5JzS33ZhPqSgldYg7ibtqF207AvTGyNUUPlvA313xTSMsNC3gq7zw==,iv:uHXQxyE0l4Jm48SoPLYwEdJ2AKaXxDiW/M083gx3AUk=,tag:xkBkcz+r8KIgy7qId9N06g==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Oc9GHq8fke3kurw9LUP9wSjd//r4hZ//PwQ9TO9qcckyJ1m9msBwB2EPW3I=,iv:pdGFnzLA2khNAord2cVOL4aq8v2sYCPM8mMVIUbXIxo=,tag:EFzobMSxZG7xm2BgjU/q6Q==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:eHdB7/fRoCRefnqSqjTja9H1xzcp5BKWgbO2ABOEEFtSpxCIVd06JT/u0l28YKayPABEIbLYCZg2ygwwKXJMziYD70hlyX4r,iv:jitjNbYB6eBGQkeLcoLDabjV6CtdpXcSHGij7r16Fcc=,tag:8Xwi48gK3E3AH2qzxl9oPA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:rqnhda0jW5yUokGRzZ54tXssb0VcVqUGQnzruPzhExt8rPw=,iv:37fG+dnabavdTpbLBxj+SQllmuWTADxJYYgBFCqXjJ4=,tag:kmt72yPzjvAFyAFksnI6Eg==,type:str]
    ALLOWED_EMAILS: ENC[AES256_GCM,data:sozaUzBbVKhm+JiYneXu7NcpA1nnp9M=,iv:Q8J5CNLDtXAwMiF0exUh5iudSuwtk+lqMmhLuJM2FiU=,tag:U1FQ+ulVyx4Db8Qta2cqYQ==,type:str]
    LOGIN_PAGE_KEY: ENC[AES256_GCM,data:DGoLR70cQ4cI,iv:gqQLD8hP29QzfOu8lial6LSZNvKdb1VLsT2YBqerewE=,tag:9B6Iy/6/RCUvZjoiM14Ykw==,type:str]
    R2_ENDPOINT: ENC[AES256_GCM,data:pQVXFTr2oPVhsJ1F2k/0dYzAa3jsVBJHj240U0WqR+WkMviAoNIMM5k=,iv:+0kQhFB+CPgo+HHdoUnV12d3lnpBRo5mIkh6R7D+fVY=,tag:KYgQ/LvYOPRAULYuPex4GA==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:BaWuki1UmasuDFLfLN9//XCBUSFiq4CPZA==,iv:IdF8+onPbK14RQ+E5x7DyklZHjjA32C+MpUeP4VKgxE=,tag:a8D7/DWTrLjMjgf6DBgEaQ==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:U/32zWn9kopB0uudl0HbRTlO+WxqVYkLpKoeTY08ng==,iv:wGTOch5trxx85yfLNzq5jb6suNS+XLLKkBCF6pn7cHg=,tag:DPnTtQiEk8ZsWilUrKjV8A==,type:str]
    R2_BUCKET: ENC[AES256_GCM,data:hLIYTd/IXVluSw==,iv:EdOnX7G4+7sOiuQ9GvDZOXztq19ruOWZ5SEIEAeZ4Hk=,tag:bnPqrRqp28Uxkw02Rs1ebQ==,type:str]
    R2_PUBLIC_URL: ENC[AES256_GCM,data:sQUM/LWXSpR6ryOMRdC8yCijnCQU/6zhOw44WJsWJjMYDbf85anlwPXzrM7sJCT45FVXxw==,iv:zXx358K1pRxRHq6wuYoZ46CMwMiWLodLK9ysjIK2zLQ=,tag:lJWv0AJjSfCII/uAfwdtUg==,type:str]
    MAKE_WEBHOOK_URL: ENC[AES256_GCM,data:4kJFCY7ugwzrOEaVQTfm5x078Y9nkjyhyE94oIV1QeUEGm68V8JgJSQqTkJamH+3QyY6r+2pHgOdlw==,iv:ApCZcsqapRu6ojHbJQZCS6XFh04k6yDncSjzmKOH2NY=,tag:ADie6Z8vN7iVPOgulaUWcw==,type:str]
    GOOGLE_VISION_API_KEY: ENC[AES256_GCM,data:VF7bNwlz8Wah2bvBEJ9jcVt38JN2muhzSG5yZRX3I4XiScp5InMt,iv:8344YzPmnxdHEKnXsZ37YJ9Iz21tMaRw/CNUJXRE6Uo=,tag:hwgShYJ/EwDTjT8QgfEPsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN1dFMHB1djZqRlljREgy
            Y1hYZUJldGJWeCs4SExMejBuam12UXgvTGxrCmtrU2p5UTJxbFEzZmpSd2crdUJP
            cDNDMTVuSTlJai9pdDJHM0pXNlU1K0EKLS0tIEpSa3ZSY09GRUNzNHp6V3JZeU03
            ZVJkY21RcVFyRUljM1FLSVhMa3JKTk0KyI21J/3fU6ovzdH6FCBNM47fRvtaiiQb
            NboljNE085nU1yCEt3HmjPcjxCDdSySXDUGEPzK5yAWxZOpaaTy6lQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10fxsujcvpt6m4kwt36v7y7ljg7utgucwcq40hq9j2r5emay2gcwse9z20m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T19:53:58Z"
    mac: ENC[AES256_GCM,data:VbcJ+EU/I/8dtm5vmaSvrPaD7s80NhCpZ2jNJlKhcb/lPr8t2TuwdIgSyhglcEaaL54yHU+hK/16pFK3XpF8+bW2oeFTfCdY69dy2FgvcvbU24/omrWMte6zUVoTyKViHog4CqGybMvAjMeV9ZfI7F6y6bQx6oIBsPg2MYf9uPE=,iv:IXiHP8qdo7fK+kAVllorgMri2NG31ntvzSwPDlF2vDk=,tag:9YEaQqIGoaQFELNqCqjnOA==,type:str]
    version: 3.13.0
