apiVersion: v1
data:
    token: ENC[AES256_GCM,data:qM70HtLJXiYBWsqlQAbCxnCk/sw8NE9/92cT6haR0hOzuuOjiEjwl+ph9jeYwQgvJG0vWzAGwX+T+fu5XhsrbA5RGHAhG9Ra,iv:rFH4e4k0axORUNyFHhUxP9pSaJ9tYGYlyWHVyZQJSQ4=,tag:HW1Yey2bMlNgZoGKk7aoAw==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQk1ITTBVTytQeitRRDVs
            dWtGQlJnRDBQa2JOT1FjWk5aQ0UrWFB5QlgwCm9KOGl0NWdnc2xEa3laM0ZleFY4
            cm1QUVlmQTU2d2J2cTNHZWpQMDBodU0KLS0tIGdBcDIwL3AxSVVReGVmdCtJN3px
            dEk5Zm85b1lILzNYV3Yxemp1Vks5ZzQK6x6L6glvzJzkhYvTjzD0Dka4UXyMn3ga
            PpaBnY1p3XgOv/ldNxVA9U2dEJ0wGxzV39j1CM8c6lRs8oUl12AgVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10fxsujcvpt6m4kwt36v7y7ljg7utgucwcq40hq9j2r5emay2gcwse9z20m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T21:50:02Z"
    mac: ENC[AES256_GCM,data:FKa6nlQktfqzyqzoLaI9oJbjKAymzPQAA4Bq1abQjVf+EEwC9Hu3zYFn8ETFtvHMaNyuR/RRbNw4BKDjat2Grd2lOQYmoU6tOXvbWPhn9/Ksy3LQV+Pz3PePRVItOVo820gc/rKLYsRBl8O85Lz1ziXuxMFRd0r9J/bkmf4AOv4=,iv:hnfQ+e6ETMkqtFlvvt+AO6OCrzqvPrkPTy/eM0RNHXg=,tag:MNnjPDfEolDO73EUSAFKKQ==,type:str]
    version: 3.13.0
